-- Tag questions with the exam they were asked in, keyed by question index.
-- GENERATED by tools/generate_exam_sql.py from
-- questions-md/Modern_History_PYQs_grouped.md (matched against the live DB).
-- Re-run the generator rather than hand-editing this file.
-- Additive: does NOT clear existing exam values; unmatched questions stay NULL.
-- Run in: Supabase Dashboard -> SQL Editor -> New query -> Run

begin;

-- BPSC (53)
update public.questions set exam = 'BPSC'
where "index" in (250,341,342,345,349,366,367,373,432,433,457,459,461,465,466,467,468,469,470,471,507,509,514,515,516,519,560,561,562,565,571,578,579,625,630,650,656,707,716,719,821,844,845,850,852,853,854,855,907,908,909,911,924);

-- Bihar J. Service (3)
update public.questions set exam = 'Bihar J. Service'
where "index" in (624,813,817);

-- CAPF (2)
update public.questions set exam = 'CAPF'
where "index" in (234,337);

-- CDS (41)
update public.questions set exam = 'CDS'
where "index" in (167,274,275,325,334,343,351,356,358,361,363,368,369,370,531,532,533,536,539,553,555,558,559,591,592,637,639,640,641,712,713,715,877,879,880,883,901,902,905,927,930);

-- CUET (2)
update public.questions set exam = 'CUET'
where "index" in (473,926);

-- Chhatis G-PSC (2)
update public.questions set exam = 'Chhatis G-PSC'
where "index" in (435,825);

-- Jharkhand (2)
update public.questions set exam = 'Jharkhand'
where "index" in (644,709);

-- Karnataka (1)
update public.questions set exam = 'Karnataka'
where "index" in (541);

-- MPPSC (19)
update public.questions set exam = 'MPPSC'
where "index" in (327,338,520,570,574,593,664,667,818,819,865,866,868,869,913,915,916,931,932);

-- Maharashtra (5)
update public.questions set exam = 'Maharashtra'
where "index" in (651,661,917,918,929);

-- NDA (54)
update public.questions set exam = 'NDA'
where "index" in (247,252,304,313,321,330,333,335,339,340,346,347,521,522,525,526,527,567,575,576,577,594,595,614,616,618,619,622,623,653,655,662,668,698,699,700,708,718,721,789,790,791,796,797,799,801,803,804,805,806,807,870,871,937);

-- Odisha (2)
update public.questions set exam = 'Odisha'
where "index" in (710,890);

-- RRB (1)
update public.questions set exam = 'RRB'
where "index" in (260);

-- Rajasthan (1)
update public.questions set exam = 'Rajasthan'
where "index" in (889);

-- SSC CGL (1)
update public.questions set exam = 'SSC CGL'
where "index" in (569);

-- UK-PSC (2)
update public.questions set exam = 'UK-PSC'
where "index" in (315,434);

-- UP-PCS (33)
update public.questions set exam = 'UP-PCS'
where "index" in (314,316,326,348,395,413,414,415,439,441,442,446,447,448,449,450,503,506,701,702,704,808,811,812,830,832,833,837,838,840,841,842,843);

-- UP-RO (6)
update public.questions set exam = 'UP-RO'
where "index" in (329,436,437,826,827,829);

-- UPPET (2)
update public.questions set exam = 'UPPET'
where "index" in (463,923);

-- UPPSC (17)
update public.questions set exam = 'UPPSC'
where "index" in (251,332,344,371,372,566,572,587,626,628,658,659,660,663,720,912,919);

-- UPSC (32)
update public.questions set exam = 'UPSC'
where "index" in (235,324,328,336,352,353,360,364,365,451,453,462,472,479,528,529,530,547,548,549,550,551,573,629,632,635,652,875,876,921,934,935);

-- WB Prelims (14)
update public.questions set exam = 'WB Prelims'
where "index" in (474,475,476,477,540,580,581,582,583,584,585,586,657,711);

commit;
